(defun start()
	(format t "************BUZZFEED PERSONALITY QUIZ**********~%~%")
	(format t "#  Answer the Following Questions ~%")
	(setq qlty1 (ques1))
	(setq qlty2 (ques2))
	(setq qlty3 (ques3))
	(setq qlty4 (ques4))
	(setq qlty (+ qlty1 qlty2 qlty3 qlty4))
	(setq result (mod qlty 4))
	(description result )
	)

(defun ques1()
	(setq x 1)
    (format t "~%# I. Which movie do you like? ~%")
    (format t "        1. Harry Potter ~%")
    (format t "        2. Bahubali ~%")
    (format t "        3. Pokemon ~%")
    (format t "        4. DDLJ ~%")
	(loop while (= x 1) do
	    (princ "Enter Your Choice: ")  
	    (setq x1 (read))
	    (cond ((= x1 1)
	        (setq a1 10)
	        ))
	    (cond ((= x1 2) 
	        (setq a1 20)
	        ))
	    (cond ((= x1 3)
	        (setq a1 30)
	        ))
	    (cond ((= x1 4)
	        (setq a1 40)
	        ))
	    (if (or (= x1 1) (= x1 2) (= x1 3) (= x1 4))
	        (setq x 0)
	    (format t "~%Wrong Option, please re enter it: ~%")))
    (return-from ques1 a1)
    )


(defun ques2()
	(setq x 1)
	(format t "~%# QII. Which flower do you like? ~%")
	(format t "		1. Rose ~%")
	(format t "		2. Lotus ~%")
	(format t "		3. Sunflower ~%")
	(format t "		4. Jasmine ~%")
	(loop while (= x 1) do
		(princ "Enter Your Choice: ")
		(setq x2 (read))
		(cond ((= x2 1)
   			(setq a2 10)
   			))
		(cond ((= x2 2)
   			(setq a2 20)
   			))
		(cond ((= x2 3)
   			(setq a2 30)
   			))
		(cond ((= x2 4)
   			(setq a2 40)
   			))
		(if (or (= x2 1) (= x2 2) (= x2 3) (= x2 4))
	        (setq x 0)
	    (format t "~%Wrong Option, please re enter it: ~%")))
	(return-from ques2 a2)
	)

(defun ques3()
	(setq x 1)
	(format t "~%# QIII. What type of food options you will choose the most (very often) ? ~%")
	(format t "		1. If you use your grill more than your actual stove. ~%")
	(format t "		2. If your favourite food is ice cream with a cherry on top. ~%")
	(format t "		3. If your go-to happy food is pizza. ~%")
	(format t "		4. If you are always first in line at the newest food truck. ~%")
	(loop while (= x 1) do
		(princ "Enter Your Choice: ")
		(setq x3 (read))
		(cond ((= x3 1)
   			(setq a3 10)
    		))
		(cond ((= x3 2)
   			(setq a3 20)
    		))
		(cond ((= x3 3)
   			(setq a3 30)
   			))
		(cond ((= x3 4)
   			(setq a3 40)
   			))
		(if (or (= x3 1) (= x3 2) (= x3 3) (= x3 4))
	        (setq x 0)
	    (format t "~%Wrong Option, please re enter it: ~%")))
	(return-from ques3 a3)
	)

(defun ques4()
	(setq x 1)
	(format t "~%# QIV. What is your go-to color or you want to see around yourself? ~%")
	(format t "		1. Red ~%")
	(format t "		2. Blue ~%")
	(format t "		3. White ~%")
	(format t "		4. Black ~%")
	(loop while (= x 1) do
		(princ "Enter Your Choice: ")
		(setq x4 (read))
		(cond ((= x4 1)
   			(setq a4 10)
   			))
		(cond ((= x4 2)
   			(setq a4 20)
   			))
		(cond ((= x4 3)
   			(setq a4 30)
   			))
		(cond ((= x4 4)
   			(setq a4 40)
   				))
		(if (or (= x4 1) (= x4 2) (= x4 3) (= x4 4))
	        (setq x 0)
	    (format t "~%Wrong Option, please re enter it: ~%")))
	(return-from ques4 a4)
	)

(defun description(result)
	(format t "~%OH! You Belong To The Following Type Of Personality!!~%")

	(if (= result 0)
	(format t "~%You are bold, boisterous, serious, intense personality,and full of energy. Your need for adventure and spontaneous nature makes you a passionate and ambitious individual. You love tradition, family and holiday and travel to new places with your best buddies. You always strive for perfection. You like to experiment with new things and is not afraid of doing it again.~%"))
	
	(if (= result 1)
	(format t "~%You wake up full of energy, fight against the odds and try to find a way, No matter what comes in your way. You are a strong-willed and determined character, probably seeking power and prestige and who is not afraid to go after what they want. You are the sort who is always smiling, always infecting others with your warmth, and you’re the life of the party who likes a thrilled life. You can be demanding at times, perhaps, but your sophisticated decisions and will never goes out of your style. You probably like to keep a clean and tidy household, and respect that stability is an extremely important aspect of your life. ~%"))

	(if (= result 2)
	(format t "~%Oh, you are sunshine, happy, cheerful and very dramatic personality who always loves an adventure in life. You are a neat, simple, extrovert who never gives up and like to do new things in life. Nothing stops you from being bubbly and energetic, no matter how tough life is. You love to be surrounded by others and also you are a party person, very independent, self-sufficient, and detail-oriented. You are likely a risk taker who also loves things like bungee jumping or the stock market.~%"))

	(if (= result 3)
	(format t "~%You are a kind hearted, forgiving and genuine person who does not wish to hurt anyone even if you yourself are hurt. You respect everyone around yourself irrespective of what they do. You belief in love and pray for their good future. You see yourself as a simple person who is happy with life and aren’t too keen on big changes. Your style is pretty unique, down to earth and most of the time you’re reserved. In life, you prefer to be real and practical. You like to live according to your beliefs and ideals, and choose to live in harmony and peace.	~%"))

	)